// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.Data;

#nullable disable

namespace PaymentService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230302123010_addedtest2")]
    partial class addedtest2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PaymentService.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("PaymentService.Models.test2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("testid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("testid");

                    b.ToTable("Tests2");
                });

            modelBuilder.Entity("PaymentService.Models.test2", b =>
                {
                    b.HasOne("PaymentService.Models.Test", "Test")
                        .WithMany("Tests2")
                        .HasForeignKey("testid");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PaymentService.Models.Test", b =>
                {
                    b.Navigation("Tests2");
                });
#pragma warning restore 612, 618
        }
    }
}
