version: '3.4'

services:
  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice1
    ports: 
        - "5050:80"
    build:
      context: .
      dockerfile: PaymentService1/Dockerfile
  paymentservice2:
    image: ${DOCKER_REGISTRY-}paymentservice2
    ports: 
        - "5051:80"
    build:
      context: .
      dockerfile: PaymentService2/Dockerfile